hieuung:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: airflow
      password: airflow
      port: 5432
      dbname: warehouse
      schema: dev
      threads: 4

     prod:
      type: postgres
      threads: 20
      host: localhost
      port: 5432
      user: airflow
      pass: airflow
      dbname: warehouse
      schema: prod