# Example dbt_project.yml file
name: 'hieuung'
profile: 'hieuung'

model-paths: [models]
analysis-paths: [analysis]
test-paths: [tests]
seed-paths: [data]
macro-paths: [macros]
snapshot-paths: [snapshots]
target-path: target  # directory which will store compiled SQL files
clean-targets:  # directories to be removed by `dbt clean`
  - target
  - dbt_modules
# Configuring models
models:
  hieu_dbt_project:
  # Applies to all files under models/marts/core/
    marts:
      core:
        +materialized: table
      department:
        +materialized: view
        +grants:
          select: ['stakeholder']

  ## see docs: https://docs.elementary-data.com/
  elementary:
    ## elementary models will be
    ## created in the schema '<your_schema>_elementary'
    +schema: elementary
    ## To disable elementary for dev, uncomment this:
    enabled: "{{ target.name in ['prod','analytics'] }}"